///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("5c6e2315-4ca8-4136-b635-c58f62fff94e")]
    public partial class TestRepository : RepoGenBaseFolder
    {
        static TestRepository instance = new TestRepository();
        TestRepositoryFolders.ExplorerAppFolder _explorer;
        TestRepositoryFolders.EdgeVisClientAppFolder _edgevisclient;
        TestRepositoryFolders.RootWindowAppFolder _rootwindow;
        TestRepositoryFolders.EdgeVisClient1AppFolder _edgevisclient1;

        /// <summary>
        /// Gets the singleton class instance representing the TestRepository element repository.
        /// </summary>
        [RepositoryFolder("5c6e2315-4ca8-4136-b635-c58f62fff94e")]
        public static TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public TestRepository() 
            : base("TestRepository", "/", null, 0, false, "5c6e2315-4ca8-4136-b635-c58f62fff94e", ".\\RepositoryImages\\TestRepository5c6e2315.rximgres")
        {
            _explorer = new TestRepositoryFolders.ExplorerAppFolder(this);
            _edgevisclient = new TestRepositoryFolders.EdgeVisClientAppFolder(this);
            _rootwindow = new TestRepositoryFolders.RootWindowAppFolder(this);
            _edgevisclient1 = new TestRepositoryFolders.EdgeVisClient1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5c6e2315-4ca8-4136-b635-c58f62fff94e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("2a03bc88-83df-414d-ae59-b8514db99f4f")]
        public virtual TestRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The EdgeVisClient folder.
        /// </summary>
        [RepositoryFolder("9684475d-377c-4dae-a3e0-670cc5a9de21")]
        public virtual TestRepositoryFolders.EdgeVisClientAppFolder EdgeVisClient
        {
            get { return _edgevisclient; }
        }

        /// <summary>
        /// The RootWindow folder.
        /// </summary>
        [RepositoryFolder("bcccff44-eb26-4a8f-8dd0-8784515a78cc")]
        public virtual TestRepositoryFolders.RootWindowAppFolder RootWindow
        {
            get { return _rootwindow; }
        }

        /// <summary>
        /// The EdgeVisClient1 folder.
        /// </summary>
        [RepositoryFolder("4a90489f-e45d-49c7-a40f-a7b22ab699a2")]
        public virtual TestRepositoryFolders.EdgeVisClient1AppFolder EdgeVisClient1
        {
            get { return _edgevisclient1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class TestRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("2a03bc88-83df-414d-ae59-b8514db99f4f")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "2a03bc88-83df-414d-ae59-b8514db99f4f", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2a03bc88-83df-414d-ae59-b8514db99f4f")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2a03bc88-83df-414d-ae59-b8514db99f4f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The EdgeVisClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("9684475d-377c-4dae-a3e0-670cc5a9de21")]
        public partial class EdgeVisClientAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _connectInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new EdgeVisClient  folder.
            /// </summary>
            public EdgeVisClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EdgeVisClient", "/form[@title='']", parentFolder, 30000, null, true, "9684475d-377c-4dae-a3e0-670cc5a9de21", "")
            {
                _connectInfo = new RepoItemInfo(this, "CONNECT", ".//list[@automationid='Root']/listitem[@index='0']/?/?/button[@automationid='BtnConnect']/text[@caption='CONNECT']", 30000, null, "11e632a3-f7b1-451f-96f1-3885afa72521");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "cd65ada5-269d-41e1-9a10-91da50c5e5aa");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9684475d-377c-4dae-a3e0-670cc5a9de21")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9684475d-377c-4dae-a3e0-670cc5a9de21")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CONNECT item.
            /// </summary>
            [RepositoryItem("11e632a3-f7b1-451f-96f1-3885afa72521")]
            public virtual Ranorex.Text CONNECT
            {
                get
                {
                    return _connectInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CONNECT item info.
            /// </summary>
            [RepositoryItemInfo("11e632a3-f7b1-451f-96f1-3885afa72521")]
            public virtual RepoItemInfo CONNECTInfo
            {
                get
                {
                    return _connectInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("cd65ada5-269d-41e1-9a10-91da50c5e5aa")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("cd65ada5-269d-41e1-9a10-91da50c5e5aa")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The RootWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("bcccff44-eb26-4a8f-8dd0-8784515a78cc")]
        public partial class RootWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hdr700alarm2Info;
            RepoItemInfo _tblkencoderstateInfo;
            RepoItemInfo _rootInfo;
            RepoItemInfo _somepictureInfo;

            /// <summary>
            /// Creates a new RootWindow  folder.
            /// </summary>
            public RootWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RootWindow", "/form[@automationid='RootWindow']", parentFolder, 30000, null, true, "bcccff44-eb26-4a8f-8dd0-8784515a78cc", "")
            {
                _hdr700alarm2Info = new RepoItemInfo(this, "HDR700Alarm2", "tabpagelist//list[@automationid='Root']/container[2]/listitem[@automationid='HDR700_Alarm_2']", 30000, null, "886b8a9f-15f3-4e7a-b00e-01586c0b6ac7");
                _tblkencoderstateInfo = new RepoItemInfo(this, "TBlkEncoderState", "tabpagelist//list[@automationid='Root']/container[2]/listitem[@automationid='HDR700_Alarm_2']/?/?/text[@automationid='TBlkEncoderState']", 30000, null, "229d84c2-d59e-45a8-beb1-348b6f83ed06");
                _rootInfo = new RepoItemInfo(this, "Root", ".//list[@automationid='AutoLayouts']/container[@automationid='Content']/listitem[@index='3']/button[@automationid='Root']", 30000, null, "f540502b-ba77-4108-8782-31e83efc8dea");
                _somepictureInfo = new RepoItemInfo(this, "SomePicture", "?/?/picture", 30000, null, "d2c28c3b-00ae-4f0a-87fd-c5f3093d3b1a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("bcccff44-eb26-4a8f-8dd0-8784515a78cc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("bcccff44-eb26-4a8f-8dd0-8784515a78cc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HDR700Alarm2 item.
            /// </summary>
            [RepositoryItem("886b8a9f-15f3-4e7a-b00e-01586c0b6ac7")]
            public virtual Ranorex.ListItem HDR700Alarm2
            {
                get
                {
                    return _hdr700alarm2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The HDR700Alarm2 item info.
            /// </summary>
            [RepositoryItemInfo("886b8a9f-15f3-4e7a-b00e-01586c0b6ac7")]
            public virtual RepoItemInfo HDR700Alarm2Info
            {
                get
                {
                    return _hdr700alarm2Info;
                }
            }

            /// <summary>
            /// The TBlkEncoderState item.
            /// </summary>
            [RepositoryItem("229d84c2-d59e-45a8-beb1-348b6f83ed06")]
            public virtual Ranorex.Text TBlkEncoderState
            {
                get
                {
                    return _tblkencoderstateInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TBlkEncoderState item info.
            /// </summary>
            [RepositoryItemInfo("229d84c2-d59e-45a8-beb1-348b6f83ed06")]
            public virtual RepoItemInfo TBlkEncoderStateInfo
            {
                get
                {
                    return _tblkencoderstateInfo;
                }
            }

            /// <summary>
            /// The Root item.
            /// </summary>
            [RepositoryItem("f540502b-ba77-4108-8782-31e83efc8dea")]
            public virtual Ranorex.Button Root
            {
                get
                {
                    return _rootInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Root item info.
            /// </summary>
            [RepositoryItemInfo("f540502b-ba77-4108-8782-31e83efc8dea")]
            public virtual RepoItemInfo RootInfo
            {
                get
                {
                    return _rootInfo;
                }
            }

            /// <summary>
            /// The SomePicture item.
            /// </summary>
            [RepositoryItem("d2c28c3b-00ae-4f0a-87fd-c5f3093d3b1a")]
            public virtual Ranorex.Picture SomePicture
            {
                get
                {
                    return _somepictureInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The SomePicture item info.
            /// </summary>
            [RepositoryItemInfo("d2c28c3b-00ae-4f0a-87fd-c5f3093d3b1a")]
            public virtual RepoItemInfo SomePictureInfo
            {
                get
                {
                    return _somepictureInfo;
                }
            }
        }

        /// <summary>
        /// The EdgeVisClient1AppFolder folder.
        /// </summary>
        [RepositoryFolder("4a90489f-e45d-49c7-a40f-a7b22ab699a2")]
        public partial class EdgeVisClient1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new EdgeVisClient1  folder.
            /// </summary>
            public EdgeVisClient1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("EdgeVisClient1", "/contextmenu[@processname='EdgeVis Client']", parentFolder, 30000, null, false, "4a90489f-e45d-49c7-a40f-a7b22ab699a2", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/menuitem[@accessiblename='Close']", 30000, null, "08eb6997-9bf8-4eb4-ba18-1e5156f55559");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4a90489f-e45d-49c7-a40f-a7b22ab699a2")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4a90489f-e45d-49c7-a40f-a7b22ab699a2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("08eb6997-9bf8-4eb4-ba18-1e5156f55559")]
            public virtual Ranorex.MenuItem Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("08eb6997-9bf8-4eb4-ba18-1e5156f55559")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
