///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7f8acb84-816d-487d-a0f5-4c56d6c342b4")]
    public partial class Test1Repository : RepoGenBaseFolder
    {
        static Test1Repository instance = new Test1Repository();
        Test1RepositoryFolders.EdgeVisClientAppFolder _edgevisclient;
        Test1RepositoryFolders.RootWindowAppFolder _rootwindow;
        Test1RepositoryFolders.EdgeVisClient1AppFolder _edgevisclient1;
        Test1RepositoryFolders.MicrosoftEdgeAppFolder _microsoftedge;
        Test1RepositoryFolders.DemoAppAppFolder _demoapp;

        /// <summary>
        /// Gets the singleton class instance representing the Test1Repository element repository.
        /// </summary>
        [RepositoryFolder("7f8acb84-816d-487d-a0f5-4c56d6c342b4")]
        public static Test1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test1Repository() 
            : base("Test1Repository", "/", null, 0, false, "7f8acb84-816d-487d-a0f5-4c56d6c342b4", ".\\RepositoryImages\\Test1Repository7f8acb84.rximgres")
        {
            _edgevisclient = new Test1RepositoryFolders.EdgeVisClientAppFolder(this);
            _rootwindow = new Test1RepositoryFolders.RootWindowAppFolder(this);
            _edgevisclient1 = new Test1RepositoryFolders.EdgeVisClient1AppFolder(this);
            _microsoftedge = new Test1RepositoryFolders.MicrosoftEdgeAppFolder(this);
            _demoapp = new Test1RepositoryFolders.DemoAppAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7f8acb84-816d-487d-a0f5-4c56d6c342b4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EdgeVisClient folder.
        /// </summary>
        [RepositoryFolder("efc5f532-4da0-425a-be77-b724e64694cd")]
        public virtual Test1RepositoryFolders.EdgeVisClientAppFolder EdgeVisClient
        {
            get { return _edgevisclient; }
        }

        /// <summary>
        /// The RootWindow folder.
        /// </summary>
        [RepositoryFolder("1baf5f83-efe9-4a94-a6a5-aa0cd32d26c9")]
        public virtual Test1RepositoryFolders.RootWindowAppFolder RootWindow
        {
            get { return _rootwindow; }
        }

        /// <summary>
        /// The EdgeVisClient1 folder.
        /// </summary>
        [RepositoryFolder("1eba6d4f-da05-44df-b161-581b140922d7")]
        public virtual Test1RepositoryFolders.EdgeVisClient1AppFolder EdgeVisClient1
        {
            get { return _edgevisclient1; }
        }

        /// <summary>
        /// The MicrosoftEdge folder.
        /// </summary>
        [RepositoryFolder("b51c3967-6cea-4199-81f8-8a839930f4bd")]
        public virtual Test1RepositoryFolders.MicrosoftEdgeAppFolder MicrosoftEdge
        {
            get { return _microsoftedge; }
        }

        /// <summary>
        /// The DemoApp folder.
        /// </summary>
        [RepositoryFolder("63e960cd-034d-4491-b8d2-4a977b56dcdf")]
        public virtual Test1RepositoryFolders.DemoAppAppFolder DemoApp
        {
            get { return _demoapp; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class Test1RepositoryFolders
    {
        /// <summary>
        /// The EdgeVisClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("efc5f532-4da0-425a-be77-b724e64694cd")]
        public partial class EdgeVisClientAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _connectInfo;

            /// <summary>
            /// Creates a new EdgeVisClient  folder.
            /// </summary>
            public EdgeVisClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EdgeVisClient", "/form[@title='']", parentFolder, 30000, null, true, "efc5f532-4da0-425a-be77-b724e64694cd", "")
            {
                _connectInfo = new RepoItemInfo(this, "CONNECT", ".//list[@automationid='Root']/listitem[@index='0']/?/?/button[@automationid='BtnConnect']/text[@caption='CONNECT']", 30000, null, "34860008-bbd9-4ecc-9206-eb7fd488472b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("efc5f532-4da0-425a-be77-b724e64694cd")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("efc5f532-4da0-425a-be77-b724e64694cd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CONNECT item.
            /// </summary>
            [RepositoryItem("34860008-bbd9-4ecc-9206-eb7fd488472b")]
            public virtual Ranorex.Text CONNECT
            {
                get
                {
                    return _connectInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CONNECT item info.
            /// </summary>
            [RepositoryItemInfo("34860008-bbd9-4ecc-9206-eb7fd488472b")]
            public virtual RepoItemInfo CONNECTInfo
            {
                get
                {
                    return _connectInfo;
                }
            }
        }

        /// <summary>
        /// The RootWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("1baf5f83-efe9-4a94-a6a5-aa0cd32d26c9")]
        public partial class RootWindowAppFolder : RepoGenBaseFolder
        {
            Test1RepositoryFolders.MainMenuLeftFolder _mainmenuleft;
            RepoItemInfo _homeInfo;
            RepoItemInfo _somepictureInfo;

            /// <summary>
            /// Creates a new RootWindow  folder.
            /// </summary>
            public RootWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RootWindow", "/form[@automationid='RootWindow']", parentFolder, 30000, null, true, "1baf5f83-efe9-4a94-a6a5-aa0cd32d26c9", "")
            {
                _mainmenuleft = new Test1RepositoryFolders.MainMenuLeftFolder(this);
                _homeInfo = new RepoItemInfo(this, "Home", ".//button[@automationid='AddButton']/container[@caption='PART_HeaderPanel']/tabpage[@title='Home']", 30000, null, "03d53709-1b9b-424a-8e6b-d3ca8c729ee6");
                _somepictureInfo = new RepoItemInfo(this, "SomePicture", "text/picture", 30000, null, "4ab36df8-971b-4dad-98ec-b3567a08f665");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1baf5f83-efe9-4a94-a6a5-aa0cd32d26c9")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1baf5f83-efe9-4a94-a6a5-aa0cd32d26c9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("03d53709-1b9b-424a-8e6b-d3ca8c729ee6")]
            public virtual Ranorex.TabPage Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("03d53709-1b9b-424a-8e6b-d3ca8c729ee6")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The SomePicture item.
            /// </summary>
            [RepositoryItem("4ab36df8-971b-4dad-98ec-b3567a08f665")]
            public virtual Ranorex.Picture SomePicture
            {
                get
                {
                    return _somepictureInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The SomePicture item info.
            /// </summary>
            [RepositoryItemInfo("4ab36df8-971b-4dad-98ec-b3567a08f665")]
            public virtual RepoItemInfo SomePictureInfo
            {
                get
                {
                    return _somepictureInfo;
                }
            }

            /// <summary>
            /// The MainMenuLeft folder.
            /// </summary>
            [RepositoryFolder("715e7dfe-d781-44a9-8106-041ce2ca36c0")]
            public virtual Test1RepositoryFolders.MainMenuLeftFolder MainMenuLeft
            {
                get { return _mainmenuleft; }
            }
        }

        /// <summary>
        /// The MainMenuLeftFolder folder.
        /// </summary>
        [RepositoryFolder("715e7dfe-d781-44a9-8106-041ce2ca36c0")]
        public partial class MainMenuLeftFolder : RepoGenBaseFolder
        {
            RepoItemInfo _alertsInfo;
            RepoItemInfo _ext735dbInfo;
            RepoItemInfo _mitemmapInfo;

            /// <summary>
            /// Creates a new MainMenuLeft  folder.
            /// </summary>
            public MainMenuLeftFolder(RepoGenBaseFolder parentFolder) :
                    base("MainMenuLeft", ".//menubar[@automationid='MainMenuLeft']", parentFolder, 30000, null, false, "715e7dfe-d781-44a9-8106-041ce2ca36c0", "")
            {
                _alertsInfo = new RepoItemInfo(this, "Alerts", "menuitem[@automationid='MItemAlerts']/text[@caption='Alerts']", 30000, null, "2b0486eb-a4cf-4015-9a4f-c7b05a95ef64");
                _ext735dbInfo = new RepoItemInfo(this, "Ext735Db", "menuitem[@automationid='MItemHome']/text[@caption='ext-735-db']", 30000, null, "7ca12ce2-9fef-48d5-ae93-782bbf9b1bc4");
                _mitemmapInfo = new RepoItemInfo(this, "MItemMap", "menuitem[@automationid='MItemMap']", 30000, null, "c4ba6e9f-e0bd-47c1-a0ac-e7da0ae2b8fb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("715e7dfe-d781-44a9-8106-041ce2ca36c0")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("715e7dfe-d781-44a9-8106-041ce2ca36c0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Alerts item.
            /// </summary>
            [RepositoryItem("2b0486eb-a4cf-4015-9a4f-c7b05a95ef64")]
            public virtual Ranorex.Text Alerts
            {
                get
                {
                    return _alertsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Alerts item info.
            /// </summary>
            [RepositoryItemInfo("2b0486eb-a4cf-4015-9a4f-c7b05a95ef64")]
            public virtual RepoItemInfo AlertsInfo
            {
                get
                {
                    return _alertsInfo;
                }
            }

            /// <summary>
            /// The Ext735Db item.
            /// </summary>
            [RepositoryItem("7ca12ce2-9fef-48d5-ae93-782bbf9b1bc4")]
            public virtual Ranorex.Text Ext735Db
            {
                get
                {
                    return _ext735dbInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Ext735Db item info.
            /// </summary>
            [RepositoryItemInfo("7ca12ce2-9fef-48d5-ae93-782bbf9b1bc4")]
            public virtual RepoItemInfo Ext735DbInfo
            {
                get
                {
                    return _ext735dbInfo;
                }
            }

            /// <summary>
            /// The MItemMap item.
            /// </summary>
            [RepositoryItem("c4ba6e9f-e0bd-47c1-a0ac-e7da0ae2b8fb")]
            public virtual Ranorex.MenuItem MItemMap
            {
                get
                {
                    return _mitemmapInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MItemMap item info.
            /// </summary>
            [RepositoryItemInfo("c4ba6e9f-e0bd-47c1-a0ac-e7da0ae2b8fb")]
            public virtual RepoItemInfo MItemMapInfo
            {
                get
                {
                    return _mitemmapInfo;
                }
            }
        }

        /// <summary>
        /// The EdgeVisClient1AppFolder folder.
        /// </summary>
        [RepositoryFolder("1eba6d4f-da05-44df-b161-581b140922d7")]
        public partial class EdgeVisClient1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new EdgeVisClient1  folder.
            /// </summary>
            public EdgeVisClient1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("EdgeVisClient1", "/contextmenu[@processname='EdgeVis Client']", parentFolder, 30000, null, false, "1eba6d4f-da05-44df-b161-581b140922d7", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/menuitem[@accessiblename='Close']", 30000, null, "6d9cb83d-23f6-43bc-a740-7778cbad2ef8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1eba6d4f-da05-44df-b161-581b140922d7")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1eba6d4f-da05-44df-b161-581b140922d7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("6d9cb83d-23f6-43bc-a740-7778cbad2ef8")]
            public virtual Ranorex.MenuItem Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("6d9cb83d-23f6-43bc-a740-7778cbad2ef8")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The MicrosoftEdgeAppFolder folder.
        /// </summary>
        [RepositoryFolder("b51c3967-6cea-4199-81f8-8a839930f4bd")]
        public partial class MicrosoftEdgeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _mnavswipescrollerInfo;

            /// <summary>
            /// Creates a new MicrosoftEdge  folder.
            /// </summary>
            public MicrosoftEdgeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MicrosoftEdge", "/winapp[@packagename='Microsoft.MicrosoftEdge']", parentFolder, 30000, null, true, "b51c3967-6cea-4199-81f8-8a839930f4bd", "")
            {
                _mnavswipescrollerInfo = new RepoItemInfo(this, "MNavSwipeScroller", "?/?/container[@automationid='m_navSwipeScroller']", 30000, null, "8b5812d9-5b63-43a9-a8de-3815b335652b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b51c3967-6cea-4199-81f8-8a839930f4bd")]
            public virtual Ranorex.WindowsApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WindowsApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b51c3967-6cea-4199-81f8-8a839930f4bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MNavSwipeScroller item.
            /// </summary>
            [RepositoryItem("8b5812d9-5b63-43a9-a8de-3815b335652b")]
            public virtual Ranorex.Container MNavSwipeScroller
            {
                get
                {
                    return _mnavswipescrollerInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The MNavSwipeScroller item info.
            /// </summary>
            [RepositoryItemInfo("8b5812d9-5b63-43a9-a8de-3815b335652b")]
            public virtual RepoItemInfo MNavSwipeScrollerInfo
            {
                get
                {
                    return _mnavswipescrollerInfo;
                }
            }
        }

        /// <summary>
        /// The DemoAppAppFolder folder.
        /// </summary>
        [RepositoryFolder("63e960cd-034d-4491-b8d2-4a977b56dcdf")]
        public partial class DemoAppAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new DemoApp  folder.
            /// </summary>
            public DemoAppAppFolder(RepoGenBaseFolder parentFolder) :
                    base("DemoApp", "/element", parentFolder, 30000, null, false, "63e960cd-034d-4491-b8d2-4a977b56dcdf", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("63e960cd-034d-4491-b8d2-4a977b56dcdf")]
            public virtual Ranorex.Unknown Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("63e960cd-034d-4491-b8d2-4a977b56dcdf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
