///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EdgeVis_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the EdgeVis_TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("09fdfa38-e2ba-441a-8783-f08322a6ab74")]
    public partial class EdgeVis_TestRepository : RepoGenBaseFolder
    {
        static EdgeVis_TestRepository instance = new EdgeVis_TestRepository();
        EdgeVis_TestRepositoryFolders.ExplorerAppFolder _explorer;
        EdgeVis_TestRepositoryFolders.EdgeVisClientAppFolder _edgevisclient;
        EdgeVis_TestRepositoryFolders.RootWindowAppFolder _rootwindow;

        /// <summary>
        /// Gets the singleton class instance representing the EdgeVis_TestRepository element repository.
        /// </summary>
        [RepositoryFolder("09fdfa38-e2ba-441a-8783-f08322a6ab74")]
        public static EdgeVis_TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public EdgeVis_TestRepository() 
            : base("EdgeVis_TestRepository", "/", null, 0, false, "09fdfa38-e2ba-441a-8783-f08322a6ab74", ".\\RepositoryImages\\EdgeVis_TestRepository09fdfa38.rximgres")
        {
            _explorer = new EdgeVis_TestRepositoryFolders.ExplorerAppFolder(this);
            _edgevisclient = new EdgeVis_TestRepositoryFolders.EdgeVisClientAppFolder(this);
            _rootwindow = new EdgeVis_TestRepositoryFolders.RootWindowAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("09fdfa38-e2ba-441a-8783-f08322a6ab74")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("0b5965bc-9c1c-4f75-b7c5-9de3117440c0")]
        public virtual EdgeVis_TestRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The EdgeVisClient folder.
        /// </summary>
        [RepositoryFolder("4f0f4efd-0454-4f76-b765-2aee21e8c791")]
        public virtual EdgeVis_TestRepositoryFolders.EdgeVisClientAppFolder EdgeVisClient
        {
            get { return _edgevisclient; }
        }

        /// <summary>
        /// The RootWindow folder.
        /// </summary>
        [RepositoryFolder("97526d8d-b5a8-4d5a-9e36-96e40a27d955")]
        public virtual EdgeVis_TestRepositoryFolders.RootWindowAppFolder RootWindow
        {
            get { return _rootwindow; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class EdgeVis_TestRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("0b5965bc-9c1c-4f75-b7c5-9de3117440c0")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _edgevisclient1runningwindowInfo;
            RepoItemInfo _ranorexstudio1runningwindowInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "0b5965bc-9c1c-4f75-b7c5-9de3117440c0", "")
            {
                _edgevisclient1runningwindowInfo = new RepoItemInfo(this, "EdgeVisClient1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[14]", 30000, null, "81d6d910-8822-434b-9b93-ec95b3e094c4");
                _ranorexstudio1runningwindowInfo = new RepoItemInfo(this, "RanorexStudio1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[20]", 30000, null, "7aba316f-e7bd-48a6-8ebe-c1a07ed48fd1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("0b5965bc-9c1c-4f75-b7c5-9de3117440c0")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("0b5965bc-9c1c-4f75-b7c5-9de3117440c0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EdgeVisClient1RunningWindow item.
            /// </summary>
            [RepositoryItem("81d6d910-8822-434b-9b93-ec95b3e094c4")]
            public virtual Ranorex.Button EdgeVisClient1RunningWindow
            {
                get
                {
                    return _edgevisclient1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EdgeVisClient1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("81d6d910-8822-434b-9b93-ec95b3e094c4")]
            public virtual RepoItemInfo EdgeVisClient1RunningWindowInfo
            {
                get
                {
                    return _edgevisclient1runningwindowInfo;
                }
            }

            /// <summary>
            /// The RanorexStudio1RunningWindow item.
            /// </summary>
            [RepositoryItem("7aba316f-e7bd-48a6-8ebe-c1a07ed48fd1")]
            public virtual Ranorex.Button RanorexStudio1RunningWindow
            {
                get
                {
                    return _ranorexstudio1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RanorexStudio1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("7aba316f-e7bd-48a6-8ebe-c1a07ed48fd1")]
            public virtual RepoItemInfo RanorexStudio1RunningWindowInfo
            {
                get
                {
                    return _ranorexstudio1runningwindowInfo;
                }
            }
        }

        /// <summary>
        /// The EdgeVisClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("4f0f4efd-0454-4f76-b765-2aee21e8c791")]
        public partial class EdgeVisClientAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _connectInfo;
            RepoItemInfo _cancelInfo;
            RepoItemInfo _connect1Info;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new EdgeVisClient  folder.
            /// </summary>
            public EdgeVisClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EdgeVisClient", "/form[@title='']", parentFolder, 30000, null, true, "4f0f4efd-0454-4f76-b765-2aee21e8c791", "")
            {
                _connectInfo = new RepoItemInfo(this, "CONNECT", ".//list[@automationid='Root']/listitem[@index='1']/?/?/button[@automationid='BtnConnect']/text[@caption='CONNECT']", 30000, null, "01ea2595-fdf2-4f80-9eef-ab42c314033b");
                _cancelInfo = new RepoItemInfo(this, "CANCEL", ".//button[@automationid='BtnCancel']/text[@caption='CANCEL']", 30000, null, "029f21aa-ae3b-464e-8c77-c14015feed97");
                _connect1Info = new RepoItemInfo(this, "CONNECT1", ".//list[@automationid='Root']/listitem[@index='0']/?/?/button[@automationid='BtnConnect']/text[@caption='CONNECT']", 30000, null, "3ecdeb24-44bd-48d8-b8b1-aeda5a567fbd");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "dfec8f3d-dde9-411a-b9da-abcce9950a62");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4f0f4efd-0454-4f76-b765-2aee21e8c791")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4f0f4efd-0454-4f76-b765-2aee21e8c791")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CONNECT item.
            /// </summary>
            [RepositoryItem("01ea2595-fdf2-4f80-9eef-ab42c314033b")]
            public virtual Ranorex.Text CONNECT
            {
                get
                {
                    return _connectInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CONNECT item info.
            /// </summary>
            [RepositoryItemInfo("01ea2595-fdf2-4f80-9eef-ab42c314033b")]
            public virtual RepoItemInfo CONNECTInfo
            {
                get
                {
                    return _connectInfo;
                }
            }

            /// <summary>
            /// The CANCEL item.
            /// </summary>
            [RepositoryItem("029f21aa-ae3b-464e-8c77-c14015feed97")]
            public virtual Ranorex.Text CANCEL
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CANCEL item info.
            /// </summary>
            [RepositoryItemInfo("029f21aa-ae3b-464e-8c77-c14015feed97")]
            public virtual RepoItemInfo CANCELInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }

            /// <summary>
            /// The CONNECT1 item.
            /// </summary>
            [RepositoryItem("3ecdeb24-44bd-48d8-b8b1-aeda5a567fbd")]
            public virtual Ranorex.Text CONNECT1
            {
                get
                {
                    return _connect1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CONNECT1 item info.
            /// </summary>
            [RepositoryItemInfo("3ecdeb24-44bd-48d8-b8b1-aeda5a567fbd")]
            public virtual RepoItemInfo CONNECT1Info
            {
                get
                {
                    return _connect1Info;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("dfec8f3d-dde9-411a-b9da-abcce9950a62")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("dfec8f3d-dde9-411a-b9da-abcce9950a62")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The RootWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("97526d8d-b5a8-4d5a-9e36-96e40a27d955")]
        public partial class RootWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _tblkencodernameInfo;
            RepoItemInfo _hdr700alarm2Info;
            RepoItemInfo _rootInfo;

            /// <summary>
            /// Creates a new RootWindow  folder.
            /// </summary>
            public RootWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RootWindow", "/form[@automationid='RootWindow']", parentFolder, 30000, null, true, "97526d8d-b5a8-4d5a-9e36-96e40a27d955", "")
            {
                _tblkencodernameInfo = new RepoItemInfo(this, "TBlkEncoderName", "tabpagelist//list[@automationid='Root']/container[2]/listitem[@automationid='HDR700_Alarm_2']/?/?/text[@automationid='TBlkEncoderName']", 30000, null, "e2edc050-1914-45ba-9932-34855a4122ed");
                _hdr700alarm2Info = new RepoItemInfo(this, "HDR700Alarm2", "tabpagelist//list[@automationid='Root']/container[2]/listitem[@automationid='HDR700_Alarm_2']", 30000, null, "0ff8e8d9-fe03-4f8a-b249-e4cdc4b48124");
                _rootInfo = new RepoItemInfo(this, "Root", ".//list[@automationid='AutoLayouts']/container/listitem[@index='1']/button[@automationid='Root']", 30000, null, "3b503bc8-4c69-48d3-b817-83c99f645f7e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("97526d8d-b5a8-4d5a-9e36-96e40a27d955")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("97526d8d-b5a8-4d5a-9e36-96e40a27d955")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TBlkEncoderName item.
            /// </summary>
            [RepositoryItem("e2edc050-1914-45ba-9932-34855a4122ed")]
            public virtual Ranorex.Text TBlkEncoderName
            {
                get
                {
                    return _tblkencodernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TBlkEncoderName item info.
            /// </summary>
            [RepositoryItemInfo("e2edc050-1914-45ba-9932-34855a4122ed")]
            public virtual RepoItemInfo TBlkEncoderNameInfo
            {
                get
                {
                    return _tblkencodernameInfo;
                }
            }

            /// <summary>
            /// The HDR700Alarm2 item.
            /// </summary>
            [RepositoryItem("0ff8e8d9-fe03-4f8a-b249-e4cdc4b48124")]
            public virtual Ranorex.ListItem HDR700Alarm2
            {
                get
                {
                    return _hdr700alarm2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The HDR700Alarm2 item info.
            /// </summary>
            [RepositoryItemInfo("0ff8e8d9-fe03-4f8a-b249-e4cdc4b48124")]
            public virtual RepoItemInfo HDR700Alarm2Info
            {
                get
                {
                    return _hdr700alarm2Info;
                }
            }

            /// <summary>
            /// The Root item.
            /// </summary>
            [RepositoryItem("3b503bc8-4c69-48d3-b817-83c99f645f7e")]
            public virtual Ranorex.Button Root
            {
                get
                {
                    return _rootInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Root item info.
            /// </summary>
            [RepositoryItemInfo("3b503bc8-4c69-48d3-b817-83c99f645f7e")]
            public virtual RepoItemInfo RootInfo
            {
                get
                {
                    return _rootInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
