///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace EdgeVISClient_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the EdgeVISClient_TestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("ae0e42e0-1a95-407b-adc6-3216e3fba618")]
    public partial class EdgeVISClient_TestRepository : RepoGenBaseFolder
    {
        static EdgeVISClient_TestRepository instance = new EdgeVISClient_TestRepository();
        EdgeVISClient_TestRepositoryFolders.EdgeVisClientAppFolder _edgevisclient;
        EdgeVISClient_TestRepositoryFolders.RootWindowAppFolder _rootwindow;
        EdgeVISClient_TestRepositoryFolders.ExplorerAppFolder _explorer;
        EdgeVISClient_TestRepositoryFolders.EdgeVisClient1AppFolder _edgevisclient1;

        /// <summary>
        /// Gets the singleton class instance representing the EdgeVISClient_TestRepository element repository.
        /// </summary>
        [RepositoryFolder("ae0e42e0-1a95-407b-adc6-3216e3fba618")]
        public static EdgeVISClient_TestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public EdgeVISClient_TestRepository() 
            : base("EdgeVISClient_TestRepository", "/", null, 0, false, "ae0e42e0-1a95-407b-adc6-3216e3fba618", ".\\RepositoryImages\\EdgeVISClient_TestRepositoryae0e42e0.rximgres")
        {
            _edgevisclient = new EdgeVISClient_TestRepositoryFolders.EdgeVisClientAppFolder(this);
            _rootwindow = new EdgeVISClient_TestRepositoryFolders.RootWindowAppFolder(this);
            _explorer = new EdgeVISClient_TestRepositoryFolders.ExplorerAppFolder(this);
            _edgevisclient1 = new EdgeVISClient_TestRepositoryFolders.EdgeVisClient1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("ae0e42e0-1a95-407b-adc6-3216e3fba618")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The EdgeVisClient folder.
        /// </summary>
        [RepositoryFolder("b23ce785-3189-46d3-97f8-4319f5c5a6f4")]
        public virtual EdgeVISClient_TestRepositoryFolders.EdgeVisClientAppFolder EdgeVisClient
        {
            get { return _edgevisclient; }
        }

        /// <summary>
        /// The RootWindow folder.
        /// </summary>
        [RepositoryFolder("a58c5db0-ce8b-4ed8-a226-0691959848f4")]
        public virtual EdgeVISClient_TestRepositoryFolders.RootWindowAppFolder RootWindow
        {
            get { return _rootwindow; }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("46664ba2-b71c-4488-9a36-3b361403ba85")]
        public virtual EdgeVISClient_TestRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The EdgeVisClient1 folder.
        /// </summary>
        [RepositoryFolder("840d74ff-15a5-4d72-9f5e-bdeb442b23ac")]
        public virtual EdgeVISClient_TestRepositoryFolders.EdgeVisClient1AppFolder EdgeVisClient1
        {
            get { return _edgevisclient1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class EdgeVISClient_TestRepositoryFolders
    {
        /// <summary>
        /// The EdgeVisClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("b23ce785-3189-46d3-97f8-4319f5c5a6f4")]
        public partial class EdgeVisClientAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _connectInfo;
            RepoItemInfo _connect1Info;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new EdgeVisClient  folder.
            /// </summary>
            public EdgeVisClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("EdgeVisClient", "/form[@title='']", parentFolder, 30000, null, true, "b23ce785-3189-46d3-97f8-4319f5c5a6f4", "")
            {
                _connectInfo = new RepoItemInfo(this, "CONNECT", ".//list[@automationid='Root']/listitem[@index='1']/?/?/button[@automationid='BtnConnect']/text[@caption='CONNECT']", 30000, null, "712c41a3-6e96-41de-9848-734088d7a080");
                _connect1Info = new RepoItemInfo(this, "CONNECT1", ".//list[@automationid='Root']/listitem[@index='0']/?/?/button[@automationid='BtnConnect']/text[@caption='CONNECT']", 30000, null, "63706248-78c7-4c68-b513-2c2b23ce97d0");
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/button[@accessiblename='Close']", 30000, null, "ed8edb9c-3804-476c-b861-46cb155d569b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b23ce785-3189-46d3-97f8-4319f5c5a6f4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b23ce785-3189-46d3-97f8-4319f5c5a6f4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CONNECT item.
            /// </summary>
            [RepositoryItem("712c41a3-6e96-41de-9848-734088d7a080")]
            public virtual Ranorex.Text CONNECT
            {
                get
                {
                    return _connectInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CONNECT item info.
            /// </summary>
            [RepositoryItemInfo("712c41a3-6e96-41de-9848-734088d7a080")]
            public virtual RepoItemInfo CONNECTInfo
            {
                get
                {
                    return _connectInfo;
                }
            }

            /// <summary>
            /// The CONNECT1 item.
            /// </summary>
            [RepositoryItem("63706248-78c7-4c68-b513-2c2b23ce97d0")]
            public virtual Ranorex.Text CONNECT1
            {
                get
                {
                    return _connect1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The CONNECT1 item info.
            /// </summary>
            [RepositoryItemInfo("63706248-78c7-4c68-b513-2c2b23ce97d0")]
            public virtual RepoItemInfo CONNECT1Info
            {
                get
                {
                    return _connect1Info;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("ed8edb9c-3804-476c-b861-46cb155d569b")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("ed8edb9c-3804-476c-b861-46cb155d569b")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

        /// <summary>
        /// The RootWindowAppFolder folder.
        /// </summary>
        [RepositoryFolder("a58c5db0-ce8b-4ed8-a226-0691959848f4")]
        public partial class RootWindowAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hdr700alarm2Info;
            RepoItemInfo _rootInfo;
            RepoItemInfo _partclosebtnInfo;
            RepoItemInfo _tblkencodernameInfo;
            RepoItemInfo _ip470test2Info;
            RepoItemInfo _homeInfo;
            RepoItemInfo _ext735dbInfo;
            RepoItemInfo _mitemhomeInfo;
            RepoItemInfo _root1Info;
            RepoItemInfo _alertsInfo;
            RepoItemInfo _partclosebtn1Info;
            RepoItemInfo _mitemmapInfo;
            RepoItemInfo _home1Info;
            RepoItemInfo _somepictureInfo;
            RepoItemInfo _onlineInfo;

            /// <summary>
            /// Creates a new RootWindow  folder.
            /// </summary>
            public RootWindowAppFolder(RepoGenBaseFolder parentFolder) :
                    base("RootWindow", "/form[@automationid='RootWindow']", parentFolder, 30000, null, true, "a58c5db0-ce8b-4ed8-a226-0691959848f4", "")
            {
                _hdr700alarm2Info = new RepoItemInfo(this, "HDR700Alarm2", "tabpagelist//list[@automationid='Root']/container[2]/listitem[@automationid='HDR700_Alarm_2']", 30000, null, "1ad523ae-3af8-4845-a5f0-04ddade105bd");
                _rootInfo = new RepoItemInfo(this, "Root", ".//list[@automationid='AutoLayouts']/container[@automationid='Content']/listitem[@index='0']/button[@automationid='Root']", 30000, null, "23d58f0e-bf5e-4c29-9db7-07401a2f683a");
                _partclosebtnInfo = new RepoItemInfo(this, "PARTCloseBtn", ".//button[@automationid='AddButton']/?/?/tabpage[@title='IP470_Test_2']/button[@automationid='PART_CloseBtn']", 30000, null, "696b281f-13d1-4ca0-9253-d7cfa9c78186");
                _tblkencodernameInfo = new RepoItemInfo(this, "TBlkEncoderName", "tabpagelist//list[@automationid='Root']/container[2]/listitem[@automationid='HDR700_Alarm_2']/?/?/text[@automationid='TBlkEncoderName']", 30000, null, "c4dc877f-4bb7-4559-8165-db377c3092cd");
                _ip470test2Info = new RepoItemInfo(this, "IP470Test2", "tabpagelist//list[@automationid='Root']/container[2]/listitem[@automationid='IP470_Test_2']", 30000, null, "8226c367-2da6-4685-aaaf-6959e62bcf13");
                _homeInfo = new RepoItemInfo(this, "Home", ".//button[@automationid='AddButton']/tabpage[@title='Home']", 30000, null, "d0e24e71-8136-4899-bd84-87a551f73966");
                _ext735dbInfo = new RepoItemInfo(this, "Ext735Db", ".//menubar[@automationid='MainMenuLeft']/menuitem[@automationid='MItemHome']/text[@caption='ext-735-db']", 30000, null, "79f27a8e-037f-42cc-930e-b3ac8087e197");
                _mitemhomeInfo = new RepoItemInfo(this, "MItemHome", ".//menubar[@automationid='MainMenuLeft']/menuitem[@automationid='MItemHome']", 30000, null, "60e20d4e-968a-468d-b272-df55e85b4120");
                _root1Info = new RepoItemInfo(this, "Root1", ".//list[@automationid='AutoLayouts']/container[@automationid='Content']/listitem[@index='1']/button[@automationid='Root']", 30000, null, "be6f3c04-e66b-4a80-ac81-08c20a357736");
                _alertsInfo = new RepoItemInfo(this, "Alerts", ".//menubar[@automationid='MainMenuLeft']/menuitem[@automationid='MItemAlerts']/text[@caption='Alerts']", 30000, null, "183dc0af-3ffa-4137-94cd-7df5a358089e");
                _partclosebtn1Info = new RepoItemInfo(this, "PARTCloseBtn1", ".//button[@automationid='AddButton']/?/?/tabpage[@title='Alerts']/button[@automationid='PART_CloseBtn']", 30000, null, "0fa69ab3-bf59-46df-b66c-67d6b479d574");
                _mitemmapInfo = new RepoItemInfo(this, "MItemMap", ".//menubar[@automationid='MainMenuLeft']/menuitem[@automationid='MItemMap']", 30000, null, "fc8f59e7-d771-4517-a379-fff0558af9ae");
                _home1Info = new RepoItemInfo(this, "Home1", ".//button[@automationid='AddButton']/?/?/tabpage[@title='Home']/text[@caption='Home']", 30000, null, "3878a5ca-df9b-4f20-982c-64130b175442");
                _somepictureInfo = new RepoItemInfo(this, "SomePicture", "text/picture", 30000, null, "ea053170-3097-462a-8143-ccb20d9fa07f");
                _onlineInfo = new RepoItemInfo(this, "ONLINE", "tabpagelist//container[@automationid='headerGrid']/button[@automationid='TBtnConnected']/text[@caption='ONLINE']", 30000, null, "4283e32f-f924-4b04-9593-06d636235dcd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a58c5db0-ce8b-4ed8-a226-0691959848f4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a58c5db0-ce8b-4ed8-a226-0691959848f4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HDR700Alarm2 item.
            /// </summary>
            [RepositoryItem("1ad523ae-3af8-4845-a5f0-04ddade105bd")]
            public virtual Ranorex.ListItem HDR700Alarm2
            {
                get
                {
                    return _hdr700alarm2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The HDR700Alarm2 item info.
            /// </summary>
            [RepositoryItemInfo("1ad523ae-3af8-4845-a5f0-04ddade105bd")]
            public virtual RepoItemInfo HDR700Alarm2Info
            {
                get
                {
                    return _hdr700alarm2Info;
                }
            }

            /// <summary>
            /// The Root item.
            /// </summary>
            [RepositoryItem("23d58f0e-bf5e-4c29-9db7-07401a2f683a")]
            public virtual Ranorex.Button Root
            {
                get
                {
                    return _rootInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Root item info.
            /// </summary>
            [RepositoryItemInfo("23d58f0e-bf5e-4c29-9db7-07401a2f683a")]
            public virtual RepoItemInfo RootInfo
            {
                get
                {
                    return _rootInfo;
                }
            }

            /// <summary>
            /// The PARTCloseBtn item.
            /// </summary>
            [RepositoryItem("696b281f-13d1-4ca0-9253-d7cfa9c78186")]
            public virtual Ranorex.Button PARTCloseBtn
            {
                get
                {
                    return _partclosebtnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseBtn item info.
            /// </summary>
            [RepositoryItemInfo("696b281f-13d1-4ca0-9253-d7cfa9c78186")]
            public virtual RepoItemInfo PARTCloseBtnInfo
            {
                get
                {
                    return _partclosebtnInfo;
                }
            }

            /// <summary>
            /// The TBlkEncoderName item.
            /// </summary>
            [RepositoryItem("c4dc877f-4bb7-4559-8165-db377c3092cd")]
            public virtual Ranorex.Text TBlkEncoderName
            {
                get
                {
                    return _tblkencodernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TBlkEncoderName item info.
            /// </summary>
            [RepositoryItemInfo("c4dc877f-4bb7-4559-8165-db377c3092cd")]
            public virtual RepoItemInfo TBlkEncoderNameInfo
            {
                get
                {
                    return _tblkencodernameInfo;
                }
            }

            /// <summary>
            /// The IP470Test2 item.
            /// </summary>
            [RepositoryItem("8226c367-2da6-4685-aaaf-6959e62bcf13")]
            public virtual Ranorex.ListItem IP470Test2
            {
                get
                {
                    return _ip470test2Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The IP470Test2 item info.
            /// </summary>
            [RepositoryItemInfo("8226c367-2da6-4685-aaaf-6959e62bcf13")]
            public virtual RepoItemInfo IP470Test2Info
            {
                get
                {
                    return _ip470test2Info;
                }
            }

            /// <summary>
            /// The Home item.
            /// </summary>
            [RepositoryItem("d0e24e71-8136-4899-bd84-87a551f73966")]
            public virtual Ranorex.TabPage Home
            {
                get
                {
                    return _homeInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Home item info.
            /// </summary>
            [RepositoryItemInfo("d0e24e71-8136-4899-bd84-87a551f73966")]
            public virtual RepoItemInfo HomeInfo
            {
                get
                {
                    return _homeInfo;
                }
            }

            /// <summary>
            /// The Ext735Db item.
            /// </summary>
            [RepositoryItem("79f27a8e-037f-42cc-930e-b3ac8087e197")]
            public virtual Ranorex.Text Ext735Db
            {
                get
                {
                    return _ext735dbInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Ext735Db item info.
            /// </summary>
            [RepositoryItemInfo("79f27a8e-037f-42cc-930e-b3ac8087e197")]
            public virtual RepoItemInfo Ext735DbInfo
            {
                get
                {
                    return _ext735dbInfo;
                }
            }

            /// <summary>
            /// The MItemHome item.
            /// </summary>
            [RepositoryItem("60e20d4e-968a-468d-b272-df55e85b4120")]
            public virtual Ranorex.MenuItem MItemHome
            {
                get
                {
                    return _mitemhomeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MItemHome item info.
            /// </summary>
            [RepositoryItemInfo("60e20d4e-968a-468d-b272-df55e85b4120")]
            public virtual RepoItemInfo MItemHomeInfo
            {
                get
                {
                    return _mitemhomeInfo;
                }
            }

            /// <summary>
            /// The Root1 item.
            /// </summary>
            [RepositoryItem("be6f3c04-e66b-4a80-ac81-08c20a357736")]
            public virtual Ranorex.Button Root1
            {
                get
                {
                    return _root1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Root1 item info.
            /// </summary>
            [RepositoryItemInfo("be6f3c04-e66b-4a80-ac81-08c20a357736")]
            public virtual RepoItemInfo Root1Info
            {
                get
                {
                    return _root1Info;
                }
            }

            /// <summary>
            /// The Alerts item.
            /// </summary>
            [RepositoryItem("183dc0af-3ffa-4137-94cd-7df5a358089e")]
            public virtual Ranorex.Text Alerts
            {
                get
                {
                    return _alertsInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Alerts item info.
            /// </summary>
            [RepositoryItemInfo("183dc0af-3ffa-4137-94cd-7df5a358089e")]
            public virtual RepoItemInfo AlertsInfo
            {
                get
                {
                    return _alertsInfo;
                }
            }

            /// <summary>
            /// The PARTCloseBtn1 item.
            /// </summary>
            [RepositoryItem("0fa69ab3-bf59-46df-b66c-67d6b479d574")]
            public virtual Ranorex.Button PARTCloseBtn1
            {
                get
                {
                    return _partclosebtn1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The PARTCloseBtn1 item info.
            /// </summary>
            [RepositoryItemInfo("0fa69ab3-bf59-46df-b66c-67d6b479d574")]
            public virtual RepoItemInfo PARTCloseBtn1Info
            {
                get
                {
                    return _partclosebtn1Info;
                }
            }

            /// <summary>
            /// The MItemMap item.
            /// </summary>
            [RepositoryItem("fc8f59e7-d771-4517-a379-fff0558af9ae")]
            public virtual Ranorex.MenuItem MItemMap
            {
                get
                {
                    return _mitemmapInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MItemMap item info.
            /// </summary>
            [RepositoryItemInfo("fc8f59e7-d771-4517-a379-fff0558af9ae")]
            public virtual RepoItemInfo MItemMapInfo
            {
                get
                {
                    return _mitemmapInfo;
                }
            }

            /// <summary>
            /// The Home1 item.
            /// </summary>
            [RepositoryItem("3878a5ca-df9b-4f20-982c-64130b175442")]
            public virtual Ranorex.Text Home1
            {
                get
                {
                    return _home1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Home1 item info.
            /// </summary>
            [RepositoryItemInfo("3878a5ca-df9b-4f20-982c-64130b175442")]
            public virtual RepoItemInfo Home1Info
            {
                get
                {
                    return _home1Info;
                }
            }

            /// <summary>
            /// The SomePicture item.
            /// </summary>
            [RepositoryItem("ea053170-3097-462a-8143-ccb20d9fa07f")]
            public virtual Ranorex.Picture SomePicture
            {
                get
                {
                    return _somepictureInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The SomePicture item info.
            /// </summary>
            [RepositoryItemInfo("ea053170-3097-462a-8143-ccb20d9fa07f")]
            public virtual RepoItemInfo SomePictureInfo
            {
                get
                {
                    return _somepictureInfo;
                }
            }

            /// <summary>
            /// The ONLINE item.
            /// </summary>
            [RepositoryItem("4283e32f-f924-4b04-9593-06d636235dcd")]
            public virtual Ranorex.Text ONLINE
            {
                get
                {
                    return _onlineInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ONLINE item info.
            /// </summary>
            [RepositoryItemInfo("4283e32f-f924-4b04-9593-06d636235dcd")]
            public virtual RepoItemInfo ONLINEInfo
            {
                get
                {
                    return _onlineInfo;
                }
            }
        }

        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("46664ba2-b71c-4488-9a36-3b361403ba85")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _edgevisclient1runningwindowInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "46664ba2-b71c-4488-9a36-3b361403ba85", "")
            {
                _edgevisclient1runningwindowInfo = new RepoItemInfo(this, "EdgeVisClient1RunningWindow", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[14]", 30000, null, "29191b25-8694-4516-8eba-abd8e5197a90");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("46664ba2-b71c-4488-9a36-3b361403ba85")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("46664ba2-b71c-4488-9a36-3b361403ba85")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EdgeVisClient1RunningWindow item.
            /// </summary>
            [RepositoryItem("29191b25-8694-4516-8eba-abd8e5197a90")]
            public virtual Ranorex.Button EdgeVisClient1RunningWindow
            {
                get
                {
                    return _edgevisclient1runningwindowInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The EdgeVisClient1RunningWindow item info.
            /// </summary>
            [RepositoryItemInfo("29191b25-8694-4516-8eba-abd8e5197a90")]
            public virtual RepoItemInfo EdgeVisClient1RunningWindowInfo
            {
                get
                {
                    return _edgevisclient1runningwindowInfo;
                }
            }
        }

        /// <summary>
        /// The EdgeVisClient1AppFolder folder.
        /// </summary>
        [RepositoryFolder("840d74ff-15a5-4d72-9f5e-bdeb442b23ac")]
        public partial class EdgeVisClient1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new EdgeVisClient1  folder.
            /// </summary>
            public EdgeVisClient1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("EdgeVisClient1", "/contextmenu[@processname='EdgeVis Client']", parentFolder, 30000, null, false, "840d74ff-15a5-4d72-9f5e-bdeb442b23ac", "")
            {
                _closeInfo = new RepoItemInfo(this, "Close", "?/?/menuitem[@accessiblename='Close']", 30000, null, "762d65ea-f282-4259-8526-52c36d53ca6a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("840d74ff-15a5-4d72-9f5e-bdeb442b23ac")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("840d74ff-15a5-4d72-9f5e-bdeb442b23ac")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("762d65ea-f282-4259-8526-52c36d53ca6a")]
            public virtual Ranorex.MenuItem Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("762d65ea-f282-4259-8526-52c36d53ca6a")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
