///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace EdgeVISClient_Test
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("f85649f0-23ed-41d7-9a33-12c850852425", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the EdgeVISClient_TestRepository repository.
        /// </summary>
        public static EdgeVISClient_TestRepository repo = EdgeVISClient_TestRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.EdgeVisClient1RunningWindow' at 13;13.", repo.Explorer.EdgeVisClient1RunningWindowInfo, new RecordItemIndex(0));
            repo.Explorer.EdgeVisClient1RunningWindow.Click("13;13");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgeVisClient.CONNECT1' at 36;4.", repo.EdgeVisClient.CONNECT1Info, new RecordItemIndex(1));
            repo.EdgeVisClient.CONNECT1.Click("36;4");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'EdgeVisClient.Close' at 8;16.", repo.EdgeVisClient.CloseInfo, new RecordItemIndex(2));
            repo.EdgeVisClient.Close.Click("8;16");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RootWindow.ONLINE' at 54;70.", repo.RootWindow.ONLINEInfo, new RecordItemIndex(3));
            repo.RootWindow.ONLINE.Click("54;70");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RootWindow.HDR700Alarm2' at 301;26.", repo.RootWindow.HDR700Alarm2Info, new RecordItemIndex(4));
            repo.RootWindow.HDR700Alarm2.Click("301;26");
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
